### ISSUE TITLE
Add on for README

### ISSUE THREAD

**Issue by okyspace** [allegroai/clearml-serving#12]
Hello, after some issues raised, there are codes add on to define triton engine args (e.g. ports, triton version) but the usage of these are not updated to README nor the --help yet. 

Also it is not very clear the purpose of certain args like project name, name even after reading the --help. 
Perhaps these can be updated in the README, so easier to use it. 

This is also related to my failed attempt to use my own ClearML server and Triton setup with ClearML serving. 
Suspect it might be due to familiarisation of these args and also might have gaps in implementation. But suggest to get the args right first, so that I can test out further.

**Comment by bmartinn** [comment]
Hi @okyspace 

I'll try to shed some light on the mechanics of `clearml-serving` (If this is successful we could make it into a proper doc :) 

Basically we have two Tasks, the first is the control-plane Task, it stores the configuration on the serving engine, the models that needs to be server etc.
Task (1) will be checking for new models published in the clearml Model Repository, and updating the model-ids on the endpoint configuration the Task itself stores.
The second Task (2) is actually running the Triton serving engine itself. You can think of Task (2) as a sidecar managing the Triton server inside the Triton container (Notice Task(1) is actually executed on a different machine in a different container)
Task (2) monitors the changes of the configuration of Task (1), whenever a new endpoint or model changes, it will download into the container the new model, then configure the Triton server that is running as a subprocess next to it, to use the new model.
Task(2) will also report the serving engine statistics back to Task(1).
If you wonder why we need two Task, the reasoning is that we could have multiple instances of the Triton engine, i.e. multiple Task(2), for example Task(2a) and Task(2b) all syncing back to the main Task(1).

The arguments `--project` and `--name` will set Task (1) project/name. 
This is because all the information we need to monitor the serving engine will appear on this Task.

Does that help? What else are we missing here?

**Comment by okyspace** [comment]
@bmartinn, thanks for the clarification. These are probably missing, which I didn't manage to find them in README nor --help. 

1. usage of --engine-container, --engine-container-args to define your own triton settings. (e.g. ports, version, polling rate) which was added on in v0.3.3 if not wrong. 
2. A way to config to use own ClearML server and Triton, which I understand it might not be working as of now.

**Comment by bmartinn** [comment]
> 1. usage of --engine-container, --engine-container-args to define your own triton settings

Following on the previous example, Task (2) (running the Triton engine) is executed by the `clearml-agent` specifically it will use the default Triton engine container `nvcr.io/nvidia/tritonserver:21.03-py3` , then inside he container it will launch the sidecar process, that will in turn launch the engine monitor it. To allow the user to upgrade to latest Triton engines or custom container, we added the ability to specify the Triton container to user as well as additional docker arguments to be executed by the `cleaml-agent` when spinning the container. 

> 2. A way to config to use own ClearML server and Triton, which I understand it might not be working as of now.

ClearML-server and Triton are working, nothing to worry :)
Notice that the `clearml-server` is only the control-plane, running Task(1), it does not do the actual serving. The spinning of the serving engine itself is done via the `cleaml-agent`. 
Specifically let's assume we have `clearml-server` running on machine A (cpu-only), and machine B (gpu machine) running `clearml-agent` attached to one the the GPUs.
The `clearml-serving` (executed on a 3rd machine, say laptop), will configure the control Task (1) and spin it on the `services` queue, running on the `clearml-server`, then it configures Task (2) the serving engine, on Machine B, the GPU machine, by creating the Task and pushing it to the GPU queue.

Does that make sense ?

**Comment by okyspace** [comment]
@bmartinn, thanks for the explanation. 
Apologies for taking awhile to work on this, as was busy with other stuffs.

I tested --engine-container and it works. 
But for --engine-container-args '-p 9000:8000 -p 8001:8001 -p 8002:8002 --model-control-mode poll --repository-poll-secs 5', there are errors stating that `unknown flag: --model-control-mode`.

This is the standard flag for triton, so I couldn't figure out why triton could not find this flag. Appreciate your help.

**Comment by bmartinn** [comment]
Hi @okyspace 
I think the `"  --model-control-mode poll --repository-poll-secs 5"` are parameters that need to be passed  to the triton process, not the container launch command itself (of example the `"-p 9000:8000 -p 8001:8001 -p 8002:8002"` are port mapping arguments passed to the docker runtime when spinning the container)

If you want to change the Triton process arguments, first find for the triton Task on the clearml UI (default project DevOps name should be "triton serving engine").
Then under the Configuration tab of the Task, look for "Args"  section, and add the following key/value entries: "t_model-control-mode", "poll" and "t_repository-poll-secs", "5"
(Notice we add "t_" prefix to any argument that will be passed to the engine itself).

With all the above said, I think we should add it as a CLI argument to `clearml-serving`, wdyt?

**Comment by okyspace** [comment]
> With all the above said, I think we should add it as a CLI argument to clearml-serving, wdyt?
Yes, I think it might be beneficial to allow developer to have more detailed control of the serving engine.

**Comment by bmartinn** [comment]
> Yes, I think it might be beneficial to allow developer to have more detailed control of the serving engine.

Sounds good to me, let's add them :)

**Comment by qwaxys** [comment]
Closing this issue as inactive, feel free to open a new issue and link to this one.
