### ISSUE TITLE
add aux-config parser error

### ISSUE THREAD

**Issue by andycancado** [allegroai/clearml-serving#30]
Hello,
I'm trying to add a onnx model and specify the platform on clearml-serving model add aux-config but i have a parser error,
<img width="608" alt="Screenshot 2022-06-14 at 17 12 52" src="https://user-images.githubusercontent.com/5150628/173626928-d2236118-f728-405c-8758-86a520a97e1c.png">
on the file triton_helper.py the parser expect an int, 

<img width="823" alt="Screenshot 2022-06-14 at 17 06 46" src="https://user-images.githubusercontent.com/5150628/173627149-e95d5c6f-2743-4a2d-9e91-d646f85af590.png">

thanks for your work on clearml-serving 🙌

**Comment by bmartinn** [comment]
Hi @andycancado 
I'm so sorry for the delayed response, this issue somehow slipped through the cracks :( 

> clearml-serving model add aux-config but i have a parser error,

I think you are correct, seems the issue is [here](https://github.com/allegroai/clearml-serving/blob/826f503cf4a9b069b89eb053696d218d1ce26f47/clearml_serving/__main__.py#L474). 
What's the full command you are passing? (so that we are sure the issue is fully fixed) 


> Thanks for your work on clearml-serving 🙌

Thank you so much for say so!

**Comment by bmartinn** [comment]
@andycancado any chance you can verify the fix works?
Upgrade to the latest version with:
```
pip3 install git+https://github.com/allegroai/clearml-serving.git
```
wdyt?
